#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${ENV_FILE:-${ROOT_DIR}/.env}"

# shellcheck source=/dev/null
source "${ROOT_DIR}/scripts/common.sh"

if [[ ! -f "${ENV_FILE}" ]]; then
  echo "Missing .env file. Run: cp .env.example .env"
  exit 1
fi

NEW_FD_THEME_RELEASE_TAG="${FD_THEME_RELEASE_TAG:-}"
NEW_FD_PAGE_COMPOSER_RELEASE_TAG="${FD_PAGE_COMPOSER_RELEASE_TAG:-}"
NEW_FD_ADMIN_UI_RELEASE_TAG="${FD_ADMIN_UI_RELEASE_TAG:-}"
NEW_FD_MEMBER_RELEASE_TAG="${FD_MEMBER_RELEASE_TAG:-}"
NEW_FD_PAYMENT_RELEASE_TAG="${FD_PAYMENT_RELEASE_TAG:-}"
NEW_FD_COMMERCE_RELEASE_TAG="${FD_COMMERCE_RELEASE_TAG:-}"
NEW_FD_CONTENT_TYPES_RELEASE_TAG="${FD_CONTENT_TYPES_RELEASE_TAG:-}"
NEW_FD_FORMS_RELEASE_TAG="${FD_FORMS_RELEASE_TAG:-}"
NEW_FD_AI_ROUTER_RELEASE_TAG="${FD_AI_ROUTER_RELEASE_TAG:-}"
NEW_FD_WEBSOCKET_PUSH_RELEASE_TAG="${FD_WEBSOCKET_PUSH_RELEASE_TAG:-}"
NEW_WPGRAPHQL_RELEASE_TAG="${WPGRAPHQL_RELEASE_TAG:-}"
NEW_WPGRAPHQL_JWT_AUTH_RELEASE_TAG="${WPGRAPHQL_JWT_AUTH_RELEASE_TAG:-}"
NEW_WPGRAPHQL_TAX_QUERY_REF="${WPGRAPHQL_TAX_QUERY_REF:-}"

if [[ -z "${NEW_FD_THEME_RELEASE_TAG}" && -z "${NEW_FD_PAGE_COMPOSER_RELEASE_TAG}" && -z "${NEW_FD_ADMIN_UI_RELEASE_TAG}" && -z "${NEW_FD_MEMBER_RELEASE_TAG}" && -z "${NEW_FD_PAYMENT_RELEASE_TAG}" && -z "${NEW_FD_COMMERCE_RELEASE_TAG}" && -z "${NEW_FD_CONTENT_TYPES_RELEASE_TAG}" && -z "${NEW_FD_FORMS_RELEASE_TAG}" && -z "${NEW_FD_AI_ROUTER_RELEASE_TAG}" && -z "${NEW_FD_WEBSOCKET_PUSH_RELEASE_TAG}" && -z "${NEW_WPGRAPHQL_RELEASE_TAG}" && -z "${NEW_WPGRAPHQL_JWT_AUTH_RELEASE_TAG}" && -z "${NEW_WPGRAPHQL_TAX_QUERY_REF}" ]]; then
  echo "Nothing to update. Pass at least one release tag via environment variables."
  exit 1
fi

backup_file="${ENV_FILE}.backup-tags-$(date +%Y%m%d-%H%M%S)"
cp "${ENV_FILE}" "${backup_file}"

if [[ -n "${NEW_FD_THEME_RELEASE_TAG}" ]]; then
  set_env_value "${ENV_FILE}" "FD_THEME_RELEASE_TAG" "${NEW_FD_THEME_RELEASE_TAG}"
  load_env_file "${ENV_FILE}"
  if [[ "${AVAILABLE_FD_THEME_RELEASE_TAG:-}" == "${NEW_FD_THEME_RELEASE_TAG}" ]]; then
    unset_env_value "${ENV_FILE}" "AVAILABLE_FD_THEME_RELEASE_TAG"
  fi
fi

if [[ -n "${NEW_FD_PAGE_COMPOSER_RELEASE_TAG}" ]]; then
  set_env_value "${ENV_FILE}" "FD_PAGE_COMPOSER_RELEASE_TAG" "${NEW_FD_PAGE_COMPOSER_RELEASE_TAG}"
  load_env_file "${ENV_FILE}"
  if [[ "${AVAILABLE_FD_PAGE_COMPOSER_RELEASE_TAG:-}" == "${NEW_FD_PAGE_COMPOSER_RELEASE_TAG}" ]]; then
    unset_env_value "${ENV_FILE}" "AVAILABLE_FD_PAGE_COMPOSER_RELEASE_TAG"
  fi
fi

if [[ -n "${NEW_FD_ADMIN_UI_RELEASE_TAG}" ]]; then
  set_env_value "${ENV_FILE}" "FD_ADMIN_UI_RELEASE_TAG" "${NEW_FD_ADMIN_UI_RELEASE_TAG}"
  load_env_file "${ENV_FILE}"
  if [[ "${AVAILABLE_FD_ADMIN_UI_RELEASE_TAG:-}" == "${NEW_FD_ADMIN_UI_RELEASE_TAG}" ]]; then
    unset_env_value "${ENV_FILE}" "AVAILABLE_FD_ADMIN_UI_RELEASE_TAG"
  fi
fi

if [[ -n "${NEW_FD_MEMBER_RELEASE_TAG}" ]]; then
  set_env_value "${ENV_FILE}" "FD_MEMBER_RELEASE_TAG" "${NEW_FD_MEMBER_RELEASE_TAG}"
  load_env_file "${ENV_FILE}"
  if [[ "${AVAILABLE_FD_MEMBER_RELEASE_TAG:-}" == "${NEW_FD_MEMBER_RELEASE_TAG}" ]]; then
    unset_env_value "${ENV_FILE}" "AVAILABLE_FD_MEMBER_RELEASE_TAG"
  fi
fi

if [[ -n "${NEW_FD_PAYMENT_RELEASE_TAG}" ]]; then
  set_env_value "${ENV_FILE}" "FD_PAYMENT_RELEASE_TAG" "${NEW_FD_PAYMENT_RELEASE_TAG}"
  load_env_file "${ENV_FILE}"
  if [[ "${AVAILABLE_FD_PAYMENT_RELEASE_TAG:-}" == "${NEW_FD_PAYMENT_RELEASE_TAG}" ]]; then
    unset_env_value "${ENV_FILE}" "AVAILABLE_FD_PAYMENT_RELEASE_TAG"
  fi
fi

if [[ -n "${NEW_FD_COMMERCE_RELEASE_TAG}" ]]; then
  set_env_value "${ENV_FILE}" "FD_COMMERCE_RELEASE_TAG" "${NEW_FD_COMMERCE_RELEASE_TAG}"
  load_env_file "${ENV_FILE}"
  if [[ "${AVAILABLE_FD_COMMERCE_RELEASE_TAG:-}" == "${NEW_FD_COMMERCE_RELEASE_TAG}" ]]; then
    unset_env_value "${ENV_FILE}" "AVAILABLE_FD_COMMERCE_RELEASE_TAG"
  fi
fi

if [[ -n "${NEW_FD_CONTENT_TYPES_RELEASE_TAG}" ]]; then
  set_env_value "${ENV_FILE}" "FD_CONTENT_TYPES_RELEASE_TAG" "${NEW_FD_CONTENT_TYPES_RELEASE_TAG}"
  load_env_file "${ENV_FILE}"
  if [[ "${AVAILABLE_FD_CONTENT_TYPES_RELEASE_TAG:-}" == "${NEW_FD_CONTENT_TYPES_RELEASE_TAG}" ]]; then
    unset_env_value "${ENV_FILE}" "AVAILABLE_FD_CONTENT_TYPES_RELEASE_TAG"
  fi
fi

if [[ -n "${NEW_FD_FORMS_RELEASE_TAG}" ]]; then
  set_env_value "${ENV_FILE}" "FD_FORMS_RELEASE_TAG" "${NEW_FD_FORMS_RELEASE_TAG}"
  load_env_file "${ENV_FILE}"
  if [[ "${AVAILABLE_FD_FORMS_RELEASE_TAG:-}" == "${NEW_FD_FORMS_RELEASE_TAG}" ]]; then
    unset_env_value "${ENV_FILE}" "AVAILABLE_FD_FORMS_RELEASE_TAG"
  fi
fi

if [[ -n "${NEW_FD_AI_ROUTER_RELEASE_TAG}" ]]; then
  set_env_value "${ENV_FILE}" "FD_AI_ROUTER_RELEASE_TAG" "${NEW_FD_AI_ROUTER_RELEASE_TAG}"
  load_env_file "${ENV_FILE}"
  if [[ "${AVAILABLE_FD_AI_ROUTER_RELEASE_TAG:-}" == "${NEW_FD_AI_ROUTER_RELEASE_TAG}" ]]; then
    unset_env_value "${ENV_FILE}" "AVAILABLE_FD_AI_ROUTER_RELEASE_TAG"
  fi
fi

if [[ -n "${NEW_FD_WEBSOCKET_PUSH_RELEASE_TAG}" ]]; then
  set_env_value "${ENV_FILE}" "FD_WEBSOCKET_PUSH_RELEASE_TAG" "${NEW_FD_WEBSOCKET_PUSH_RELEASE_TAG}"
  load_env_file "${ENV_FILE}"
  if [[ "${AVAILABLE_FD_WEBSOCKET_PUSH_RELEASE_TAG:-}" == "${NEW_FD_WEBSOCKET_PUSH_RELEASE_TAG}" ]]; then
    unset_env_value "${ENV_FILE}" "AVAILABLE_FD_WEBSOCKET_PUSH_RELEASE_TAG"
  fi
fi

if [[ -n "${NEW_WPGRAPHQL_RELEASE_TAG}" ]]; then
  set_env_value "${ENV_FILE}" "WPGRAPHQL_RELEASE_TAG" "${NEW_WPGRAPHQL_RELEASE_TAG}"
  load_env_file "${ENV_FILE}"
  if [[ "${AVAILABLE_WPGRAPHQL_RELEASE_TAG:-}" == "${NEW_WPGRAPHQL_RELEASE_TAG}" ]]; then
    unset_env_value "${ENV_FILE}" "AVAILABLE_WPGRAPHQL_RELEASE_TAG"
  fi
fi

if [[ -n "${NEW_WPGRAPHQL_JWT_AUTH_RELEASE_TAG}" ]]; then
  set_env_value "${ENV_FILE}" "WPGRAPHQL_JWT_AUTH_RELEASE_TAG" "${NEW_WPGRAPHQL_JWT_AUTH_RELEASE_TAG}"
  load_env_file "${ENV_FILE}"
  if [[ "${AVAILABLE_WPGRAPHQL_JWT_AUTH_RELEASE_TAG:-}" == "${NEW_WPGRAPHQL_JWT_AUTH_RELEASE_TAG}" ]]; then
    unset_env_value "${ENV_FILE}" "AVAILABLE_WPGRAPHQL_JWT_AUTH_RELEASE_TAG"
  fi
fi

if [[ -n "${NEW_WPGRAPHQL_TAX_QUERY_REF}" ]]; then
  set_env_value "${ENV_FILE}" "WPGRAPHQL_TAX_QUERY_REF" "${NEW_WPGRAPHQL_TAX_QUERY_REF}"
  load_env_file "${ENV_FILE}"
  if [[ "${AVAILABLE_WPGRAPHQL_TAX_QUERY_REF:-}" == "${NEW_WPGRAPHQL_TAX_QUERY_REF}" ]]; then
    unset_env_value "${ENV_FILE}" "AVAILABLE_WPGRAPHQL_TAX_QUERY_REF"
  fi
fi

set_env_value "${ENV_FILE}" "LAST_WORDPRESS_ASSET_UPDATE_APPLIED_AT" "$(date -u +%Y-%m-%dT%H:%M:%SZ)"

echo "Updated WordPress asset release tags."
echo "Backup: ${backup_file}"
grep -E '^(FD_(THEME|PAGE_COMPOSER|ADMIN_UI|MEMBER|PAYMENT|COMMERCE|CONTENT_TYPES|FORMS|AI_ROUTER|WEBSOCKET_PUSH)_RELEASE_TAG|WPGRAPHQL_RELEASE_TAG|WPGRAPHQL_JWT_AUTH_RELEASE_TAG|WPGRAPHQL_TAX_QUERY_REF|AVAILABLE_(FD_(THEME|PAGE_COMPOSER|ADMIN_UI|MEMBER|PAYMENT|COMMERCE|CONTENT_TYPES|FORMS|AI_ROUTER|WEBSOCKET_PUSH)_RELEASE_TAG|WPGRAPHQL_RELEASE_TAG|WPGRAPHQL_JWT_AUTH_RELEASE_TAG|WPGRAPHQL_TAX_QUERY_REF)|LAST_WORDPRESS_ASSET_UPDATE_APPLIED_AT)=' "${ENV_FILE}" || true

ENV_FILE="${ENV_FILE}" bash "${ROOT_DIR}/scripts/report-deployment-status.sh" || true
